In [1]:
import numpy as np
import math
import cv2

In [12]:
# Let's use Grayscale for simplicity
image = cv2.imread("../../data/DatasetA/car-1.jpg")
image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

cv2.imwrite("../../output/cw2/original.png", image)


True

In [13]:
# Task A: Code a function that takes an input image, performs convolution with a given kernel, and returns the 
# resulting image

def mtrx_convolution_tfm(image, conv_kernel):

    # Create the new image canvas
    image_x = len(image[:,0])
    image_y = len(image[0,:])
    canvas = np.zeros((image_x, image_y))

    # Determine the sum of the convolution kernel to be used for the convolution calculation
    conv_kernel_sum = np.sum(conv_kernel)
    # If the kernel sum is zero then set it to 1 to avoid calculation error
    if conv_kernel_sum == 0:
        conv_kernel_sum = 1

    # The length of the convolution kernel determines the pixel kernel to process
    cv_x = int(np.shape(conv_kernel)[0])

    # Loop through image pixels to perform the convolution
    for i in range(image_x):

        # Skip the borders
        if i == image_x-cv_x:
            break
        
        for j in range(image_y):

            # Skip the borders
            if j == image_y-cv_x:
                break
            # Define the image kernel size based on the size of the convolution kernel
            image_kernel = image[i:i+cv_x, j:j+cv_x]
            
            # Determine the Convolution Result (the sum of the product of each pixel)
            conv_result = np.sum(conv_kernel * image_kernel)
            # print(image[i, j])
            result = conv_result / conv_kernel_sum
            # result = math.floor((np.sum(result)) * (1/np.sum(np.absolute(conv_kernel)))) # Issue here with one kernel - its sum is ZERO
            canvas[i, j] = result

    return canvas


In [15]:
# Part A - Code a function that takes an input image, performs convolution with a given kernel, and returns the 
# resulting image

# Test with a Gaussian like filter
conv_kernel_a = [
    [1, 1, 1],
    [1, 4, 1],
    [1, 1, 1]
]

result = mtrx_convolution_tfm(image, conv_kernel_a)

print(image[1:4, 1:4])
print(result[1:4, 1:4])

cv2.imwrite("../../output/cw2/result_A.png", result)

[[93 93 81]
 [88 88 83]
 [87 80 85]]
[[86.83333333 85.83333333 89.08333333]
 [84.         86.08333333 90.08333333]
 [84.58333333 86.5        88.41666667]]


True

In [16]:
# Part B
# Design a convolution kernel that computes, for each pixel, the average intensity value in a 3x3 region. 
# Use this kernel and the filtering function above, and save the resulting image.

# Define the convolution kernel
conv_kernel_b = np.ones((3,3))

# Perform the convolution on the image
result = mtrx_convolution_tfm(image, conv_kernel_b)

# Save the image to the output directory
cv2.imwrite("../../output/cw2/result_B.png", result)

True

In [17]:
# Part C
#Use the kernels provided below, apply the filtering function and save the resulting images. Comment 
#on the effect of each kernel.

kernel_A = [
    [1, 2, 1],
    [2, 4, 2],
    [1, 2, 1]
]

kernel_B = [
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
]

result_a = mtrx_convolution_tfm(image, kernel_A)
result_b = mtrx_convolution_tfm(image, kernel_B)

cv2.imwrite("../../output/cw2/result_C1.png", result_a)
cv2.imwrite("../../output/cw2/result_C2.png", result_b)

C:\Users\gpoel\AppData\Local\Temp\ipykernel_27076\3676412732.py:35: RuntimeWarning: divide by zero encountered in scalar divide
  result = conv_result / conv_kernel_sum
C:\Users\gpoel\AppData\Local\Temp\ipykernel_27076\3676412732.py:35: RuntimeWarning: invalid value encountered in scalar divide
  result = conv_result / conv_kernel_sum


True