In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
from utils import ICV_cw1

In [ ]:
# Task A: Write a function that takes as input an image I, rotates it by an angle θ1 and horizontally skews it by
# an angle, θ2

# Declare image and angles to be used for transformations
image = cv2.imread("../../data/test.jpg")

# Perform the transformation with both angles
result = ICV_cw1(image, 90, 45)

# Save the image in the output directory
cv2.imwrite("../../output/cw1/result_A.png", result)

In [ ]:
# Task B: Create an image that contains your name written in Arial, point 72, capital letters. Rotate clockwise
#         the image you created by 30, 60, 120 and -50 degrees. Skew the same image by 10, 40 and 60 
#         degrees. Complete the process so that all the pixels have a value. Discuss in the report the 
#         advantages and disadvantages of different approaches.

image = cv2.imread("../../data/cw1_b.png")

# Rotate image
for theta in [30, 60, 120, -50]:
    result = ICV_cw1(image, theta, theta, flag="rotate")
    cv2.imwrite(f"../../output/cw1/result_B_rot_{theta}.png", result)

# Skew image
for theta in [10, 40, 60]:
    result = ICV_cw1(image, theta, theta, flag="shear")
    cv2.imwrite(f"../../output/cw1/result_B_shear_{theta}.png", result)


In [4]:
# Task C: Analyse the results when you change the order of the two operators: R(S(I)) and S(R(I))

image = cv2.imread("../../data/test.jpg")

# Rotate the image by θ1 = 20 clockwise and then skew the result by θ2 = 50.
result = ICV_cw1(image, -20, 50, flag="rotate")
result1 = ICV_cw1(result, -20, 50, flag="shear")
cv2.imwrite("../../output/cw1/result_C_1.png", result1)

# Skew the image by θ2 = 50 and then rotate the result by θ1 = 20 clockwise
result = ICV_cw1(image, -20, 50, flag="shear")
result2 = ICV_cw1(result, -20, 50, flag="rotate")
cv2.imwrite("../../output/cw1/result_C_2.png", result2)

[[ 0.65302793  1.13075365]
 [-0.342       0.94      ]]
[[ 0.65302793  1.13075365]
 [-0.342       0.94      ]]
(3089, 2149, 3)
[[ 0.65302793  1.13075365]
 [-0.342       0.94      ]]
[[ 0.65302793  1.13075365]
 [-0.342       0.94      ]]
(3089, 2149, 3)
